#!/bin/sh

pep8 sshovel

pylint -f parseable sshovel \
  | egrep -v missing-docstring                          \
  | egrep -v 'Invalid (variable|argument) name "fd"'    \
  | egrep -v 'Invalid attribute name "f[012]"'          \
  | egrep -v 'TestFiles\] Too few public methods'       \
  | egrep -v 'SSHScrypt.checksum] Invalid variable name "f"'      \
  | egrep -v 'Rot13.encrypt] Invalid variable name "f"'           \
  | egrep -v 'Rot13.decrypt] Invalid variable name "f"'           \
  | egrep -v 'SSHEncrypter.sign] Invalid variable name "h"'       \
  | egrep -v 'SSHEncrypter.checksum] Invalid variable name "f"'   \
  | cat
