#!/usr/bin/env python
"""
sshovel - encrypt files with ssh-agent, bury your secrets

https://haz.cat/sshovel/

MIT License

Copyright (c) 2017 Edward Speyer

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

TODO:
- Handle agent errors.  agent.sign() may refuse none if we are missing
  the key, or if the agent prompts us with a dialog that we dismiss.
  We should look up keys to see if the agent has them, before using
  them to sign data?
- Harden OpenSSL parameters?
- Handle ^C
- Test with other types of ssh key.
- Test with multiple ssh keys.

"""

from collections import namedtuple
import argparse
import base64
import fcntl
import hashlib
import io
import os
import os.path
import pty
import re
import shutil
import signal
import socket
import struct
import subprocess
import sys
import tempfile
import time
import unittest


class UserException(Exception):
    """
    Exception for alerting the user with messages (and not full stack traces.)
    """
    pass


def log(message):
    script = os.path.basename(sys.argv[0])
    message = "{}: {}\n".format(script, message)
    sys.stderr.write(message)


class BinaryReader(object):
    """
    Wrapper around `struct` for reading SSH binary messages.
    """

    @classmethod
    def from_string(cls, string):
        return cls(io.BytesIO(string).read)

    def __init__(self, read_fn):
        self.read_fn = read_fn

    def byte(self):
        return self._read(1, '>B')

    def long(self):
        return self._read(4, '>L')

    def string(self):
        length = self.long()
        return self._read(length, '>%ds' % length)

    def _read(self, length, template):
        return struct.unpack(template, self.read_fn(length))[0]


class BinaryWriter(object):
    """
    Wrapper around `struct` for building a buffer of SSH binary messages.
    """

    def __init__(self):
        self.buf = io.BytesIO()

    def byte(self, value):
        return self._pack('>B', value)

    def long(self, value):
        return self._pack('>L', value)

    def string(self, value):
        string = str(value)
        length = len(string)
        return self._pack('>L%ds' % length, length, string)

    def end(self):
        return str(BinaryWriter().string(self))

    def __str__(self):
        return self.buf.getvalue()

    def _pack(self, template, *values):
        self.buf.write(struct.pack(template, *values))
        return self


class SSHKey(object):
    ALGORITHM_RSA = 'ssh-rsa'

    @classmethod
    def parse(cls, blob, comment):
        algorithm = BinaryReader.from_string(blob).string()
        return cls(algorithm, blob, comment)

    def __init__(self, algorithm, blob, comment):
        self.algorithm = algorithm
        self.blob = blob
        self.comment = comment

    def is_rsa(self):
        return self.algorithm == self.ALGORITHM_RSA


class SSHAgent(object):
    """
    Interface to a running ssh-agent(1)
    """

    # https://tools.ietf.org/id/draft-miller-ssh-agent-00.html
    AGENTC_REQUEST_IDENTITIES = 11
    AGENT_IDENTITIES_ANSWER = 12
    AGENTC_SIGN_REQUEST = 13
    AGENT_SIGN_RESPONSE = 14
    AGENT_FAILURE = 5

    SIGN_FLAG_NONE = 0
    SIGN_FLAG_RSA_SHA2_256 = 2
    SIGN_FLAG_RSA_SHA2_512 = 4

    def __init__(self, socket_path):
        self.sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM, 0)
        try:
            self.sock.connect(socket_path)
        except IOError as ex:
            raise UserException(
                "can't connect to ssh-agent socket %s: %s" % (socket_path, ex))

    def identities(self):
        self.sock.sendall(
            BinaryWriter()
            .byte(SSHAgent.AGENTC_REQUEST_IDENTITIES)
            .end())
        reader = BinaryReader(self.sock.recv)
        _ = reader.long()  # length
        response = reader.byte()
        assert response == SSHAgent.AGENT_IDENTITIES_ANSWER
        num_keys = reader.long()
        result = []
        for _ in range(num_keys):
            blob = reader.string()
            comment = reader.string()
            key = SSHKey.parse(blob, comment)
            result.append(key)
        return result

    def sign(self, key_blob, message, flags):
        self.sock.sendall(
            BinaryWriter()
            .byte(SSHAgent.AGENTC_SIGN_REQUEST)
            .string(key_blob)
            .string(message)
            .long(flags)
            .end())
        reader = BinaryReader(self.sock.recv)
        _ = reader.long()  # length
        response = reader.byte()
        if response == SSHAgent.AGENT_FAILURE:
            return None
        assert response == SSHAgent.AGENT_SIGN_RESPONSE
        signature = reader.string()
        return signature


class Cipher(object):
    """
    Interface / superclass for command line encryption tools.
    Plus some tools for finding the subclasses of Cipher.
    """

    def __init__(self, **options):
        self.options = options

    def encrypt(self, reader, writer, passphrase):
        pass

    def decrypt(self, reader, writer, passphrase):
        pass

    def name(self):
        return Cipher.name_of(self.__class__)

    @staticmethod
    def name_of(a_cls):
        return a_cls.__name__.lower().replace('cipher', '')

    @staticmethod
    def all_cipher_names():
        return [
            Cipher.name_of(cls)
            for cls in Cipher.__subclasses__()]

    @staticmethod
    def instance_of(name):
        for cls in Cipher.__subclasses__():
            if Cipher.name_of(cls) == name.lower():
                return cls()
        raise UserException("unknown cipher '{}'".format(name))


class OpenSSLCipher(Cipher):
    def encrypt(self, reader, writer, passphrase):
        self._openssl('-e', reader, writer, passphrase)

    def decrypt(self, reader, writer, passphrase):
        self._openssl('-d', reader, writer, passphrase)

    @staticmethod
    def _openssl(command, reader, writer, passphrase):
        password_read, password_write = os.pipe()
        os.write(password_write, passphrase)
        os.close(password_write)
        command = [
            'openssl', 'aes-256-cbc',
            command,
            '-a', '-salt',
            '-kfile', '/dev/fd/%d' % password_read]
        try:
            openssl = subprocess.Popen(
                command,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE)
            shutil.copyfileobj(reader, openssl.stdin)
            openssl.stdin.close()
            shutil.copyfileobj(openssl.stdout, writer)
            openssl.wait()
        finally:
            os.close(password_read)


class Expect(object):
    def __init__(self, command):
        self.command = command
        self._start()

    def expect(self, phrase, timeout):
        buf = ''
        for block in self._read(self.tty_read, timeout):
            buf += block
            if phrase in buf:
                return True
        raise Exception("EOF")

    def tty_read(self, size):
        return os.read(self.tty, size)

    def send(self, data):
        os.write(self.tty, data)

    def copy(self, reader, writer, timeout):
        for block in self._read(reader.read, timeout):
            writer.write(block)

    def finish(self):
        os.close(self.tty)
        self.stdout.close()
        return os.waitpid(self.pid, 0)

    def _start(self):
        stdin_reader, stdin_writer = os.pipe()
        stdout_reader, stdout_writer = os.pipe()

        pid, tty = pty.fork()
        if not pid:
            os.close(stdin_writer)
            os.close(stdout_reader)
            os.dup2(stdin_reader, 0)
            os.dup2(stdout_writer, 1)
            os.execvp(self.command[0], self.command)

        self._set_non_blocking(tty)
        self._set_non_blocking(stdout_reader)

        os.close(stdin_reader)
        os.close(stdout_writer)

        self.tty = tty
        self.pid = pid
        self.stdin = os.fdopen(stdin_writer, 'w')
        self.stdout = os.fdopen(stdout_reader, 'r')

    @staticmethod
    def _set_non_blocking(file_descriptor):
        fcntl.fcntl(file_descriptor, fcntl.F_SETFL, os.O_NONBLOCK)

    @staticmethod
    def _read(read_fn, timeout):
        start_time = time.time()
        while True:
            duration = time.time() - start_time
            if duration > timeout:
                raise Exception("timed out")
            block = None
            try:
                block = read_fn(1024)
                if block == '':
                    break
            except (IOError, OSError):
                time.sleep(0.1)
                continue
            yield block


class ScryptCipher(Cipher):
    """
    Interface to the scrypt(1) command line tool.
    """

    def encrypt(self, reader, writer, passphrase):
        command = ['scrypt', 'enc']
        command.extend(self.options.get('encrypt_options', []))
        command.append('-')
        self.scrypt(command, reader, writer, passphrase, passphrase)

    def decrypt(self, reader, writer, passphrase):
        command = ['scrypt', 'dec', '-']
        self.scrypt(command, reader, writer, passphrase)

    @staticmethod
    def scrypt(command, reader, writer, *passphrases):
        exp = Expect(command)
        for passphrase in passphrases:
            exp.expect('passphrase: ', 1)
            exp.send(passphrase + "\n")
        exp.copy(reader, exp.stdin, 10)
        exp.stdin.close()
        exp.copy(exp.stdout, writer, 10)
        exp.finish()


class ShovelFile(object):
    """
    Wrapper around an Cipher that uses an ssh-agent(1) to generate the
    cipher's passphrase.
    """

    MAGIC = "HAZ.CAT/SSHOVEL"
    VERSION = 1
    NONCE_SIZE = 1024

    @classmethod
    def is_shovel_file(cls, reader):
        expected_magic = cls._header('Magic', cls.MAGIC)
        length = len(expected_magic)
        actual_magic = reader.peek(len(expected_magic))[0:length]
        return actual_magic == expected_magic

    @classmethod
    def encrypt(cls, reader, ssh, key, cipher):
        nonce = hashlib.sha1(os.urandom(cls.NONCE_SIZE)).digest()
        flags = cls._signing_flags_for(key)
        signature = ssh.sign(key.blob, nonce, flags)
        passphrase = hashlib.sha1(signature).hexdigest()
        buf = io.BytesIO()
        cipher.encrypt(reader, buf, passphrase)
        buf.seek(0)
        return cls(cipher, key, nonce, buf)

    @classmethod
    def load_from(cls, reader):
        _ = cls._read_header(reader, 'Magic')
        _ = cls._read_header(reader, 'Version')
        cipher_name = cls._read_header(reader, 'Cipher')
        key_blob = cls._read_header_base64(reader, 'Key')
        comment = cls._read_header_base64(reader, 'Comment')
        nonce = cls._read_header_base64(reader, 'Nonce')
        key = SSHKey.parse(key_blob, comment)
        cipher = Cipher.instance_of(cipher_name)
        buf = io.BytesIO()
        base64.decode(reader, buf)
        return cls(cipher, key, nonce, buf)

    def __init__(self, cipher, key, nonce, encrypted_file):
        self.cipher = cipher
        self.key = key
        self.nonce = nonce
        self.encrypted_file = encrypted_file

    def save_to(self, writer):
        writer.write(self._header('Magic', self.MAGIC))
        writer.write(self._header('Version', self.VERSION))
        writer.write(self._header('Cipher', self.cipher.name()))
        writer.write(self._header('Key', base64.b64encode(self.key.blob)))
        writer.write(
            self._header('Comment', base64.b64encode(self.key.comment)))
        writer.write(self._header('Nonce', base64.b64encode(self.nonce)))
        writer.write("\r\n")
        base64.encode(self.encrypted_file, writer)

    def decrypt(self, writer, ssh):
        log('decrypting with {} and {}'.format(
            self.key.comment,
            self.cipher.name()))
        flags = self._signing_flags_for(self.key)
        signature = ssh.sign(self.key.blob, self.nonce, flags)
        if signature is None:
            raise UserException(
                "file is encrypted with a key we don't have: {}".format(
                    self.key.comment))
        passphrase = hashlib.sha1(signature).hexdigest()
        reader = self.encrypted_file
        reader.seek(0)
        self.cipher.decrypt(reader, writer, passphrase)

    @staticmethod
    def _signing_flags_for(key):
        if key.is_rsa():
            # Use SHA2 when available:
            # https://crypto.stackexchange.com/questions/15051/
            return SSHAgent.SIGN_FLAG_RSA_SHA2_512
        return SSHAgent.SIGN_FLAG_NONE

    @staticmethod
    def _read_header(reader, key):
        line = reader.readline().rstrip()
        actual_key, value = line.split(': ')
        if actual_key != key:
            raise UserException(
                "did not find expected key {} in line: {}"
                .format(key, line))
        return value

    @classmethod
    def _read_header_base64(cls, reader, key):
        value = cls._read_header(reader, key)
        return base64.b64decode(value)

    @staticmethod
    def _header(key, value):
        return '{}: {}\r\n'.format(key, value)


class Main(object):
    def __init__(self, args):
        args = self.parse_args(args)
        try:
            self._main(args)
        except UserException as ex:
            log(ex.message)
            sys.exit(1)

    def _main(self, args):
        if args.test is not None:
            unittest_args = [__file__]
            unittest_args.extend(args.test)
            unittest.main(argv=unittest_args)

        cipher = Cipher.instance_of(args.cipher)
        ssh = self.find_agent()
        keys = ssh.identities()
        if not keys:
            raise UserException("ssh agent has no keys")

        key = keys[0]
        if args.key:
            key = self.match_key(keys, args.key)

        if args.in_file == '-':
            args.in_file = '/dev/stdin'

        if args.out_file == '-':
            args.out_file = '/dev/stdout'

        # io.open's buffering gives us peek()
        reader = io.open(args.in_file, mode='rb', buffering=1024)
        writer = open(args.out_file, mode='wb')

        if args.in_file == '/dev/stdin':
            log("reading from stdin")

        if ShovelFile.is_shovel_file(reader):
            ShovelFile.load_from(reader).decrypt(writer, ssh)
        else:
            log("encrypting{} with ssh-key '{}' and {}".format(
                (writer == sys.stdout and ' to stdout' or ''),
                key.comment,
                args.cipher))
            ShovelFile.encrypt(reader, ssh, key, cipher).save_to(writer)

    @staticmethod
    def parse_args(args):
        epilogue = u"""\
examples:

  - Default is to use scrypt(1) to encrypt:

      $ shovel message.txt message.txt.enc


  - If the input is encrypted, then the default action is to decrypt:

      $ shovel message.txt.enc
      Hello, world!


  - Use a specific agent key (only needed for encrypt):

      $ shovel --key my_other_key
\u00A0
"""
        parser = argparse.ArgumentParser(
            usage='%(prog)s [--cipher CIPHER] [IN] [OUT]',
            formatter_class=argparse.RawDescriptionHelpFormatter,
            description='Encrypt files with ssh-agent, bury your secrets',
            epilog=epilogue)
        parser.add_argument(
            '--key',
            metavar='MATCH',
            help='use the ssh key whose comment matches MATCH')
        parser.add_argument(
            '--cipher',
            dest='cipher',
            default='scrypt',
            metavar='TOOL',
            choices=Cipher.all_cipher_names(),
            help='encrypt with "scrypt" (default) or "openssl"')
        parser.add_argument(
            '--test',
            nargs='*',
            metavar='ARGS',
            help='run the test suite')
        parser.add_argument(
            'in_file',
            nargs='?',
            default='-',
            metavar='IN',
            help='optional path, or "-" for stdin, which is the default')
        parser.add_argument(
            'out_file',
            nargs='?',
            default='-',
            metavar='OUT',
            help='as above, with stdout as the default')
        return parser.parse_args(args)

    @staticmethod
    def find_agent():
        socket_path = os.environ.get('SSH_AUTH_SOCK')
        if socket_path == "":
            raise UserException("SSH_AUTH_SOCK is empty or unset")
        return SSHAgent(socket_path)

    @staticmethod
    def match_key(keys, pattern):
        matches = []
        for candidate in keys:
            if pattern in candidate.comment:
                matches.append(candidate)
        if len(matches) == 1:
            return matches[0]
        elif not matches:
            raise UserException(
                "no ssh key matched '{}'; known keys: {}"
                .format(pattern, [k.comment for k in keys]))
        elif len(matches) > 2:
            raise UserException(
                "more than one key matched '{}': {}"
                .format(pattern, [k.comment for k in matches]))


class MainTest(unittest.TestCase):
    message = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

    def setUp(self):
        self.ssh_fixture = SSHTestFixture()
        os.environ['SSH_AUTH_SOCK'] = self.ssh_fixture.socket_path

    def test_encrypt(self):
        file0 = tempfile.NamedTemporaryFile()
        file0.write(self.message)
        file0.flush()
        file1 = tempfile.NamedTemporaryFile()
        file2 = tempfile.NamedTemporaryFile()
        Main(['--cipher', 'openssl', file0.name, file1.name])
        Main([file1.name, file2.name])
        actual = file2.read()
        self.assertEqual(self.message, actual)

    def tearDown(self):
        self.ssh_fixture.stop()


class BinaryWriterTest(unittest.TestCase):
    def test_writer(self):
        age, name, sales = 58, 'Sade', 23500000
        msg = BinaryWriter().string(name).byte(age).long(sales).end()
        expected = (
            '\x00\x00\x00\x0d'
            '\x00\x00\x00\x04'
            '\x53\x61\x64\x65'
            '\x3a'
            '\x01\x66\x94\xe0')
        self.assertEqual(msg, expected)


class BinaryReaderTest(unittest.TestCase):
    def test_reader(self):
        buf = io.BytesIO(
            '\x00\x00\x00\x11'
            '\x00\x00\x00\x08'
            '\x4f\x6c\x64\x66\x69\x65\x6c\x64'
            '\x40'
            '\x00\x28\x21\x70')
        msg = BinaryReader(buf.read)
        self.assertEqual(msg.long(), 17)
        self.assertEqual(msg.string(), 'Oldfield')
        self.assertEqual(msg.byte(), 64)
        self.assertEqual(msg.long(), 2630000)


class SSHTestFixture(object):
    """
    Set up a real ssh-agent(1) and load it with a test key, and provide a way
    to kill the agent.
    """

    TEST_KEY = """
-----BEGIN RSA PRIVATE KEY-----
MIICXAIBAAKBgQD0OCPZ50akyXxhyFz/JdCTZISvHJ+nFOnXMHKQzF3Q3fAbXGVM
jEU2Wer+owj6s4wxuNmd6g3XAyyomCSRoxE6txNpQ10Yay4ZUMhO3XDr3zN5WBhd
6dqDjNLsrfu5mjy9aWFZDpBYnmRnOQBeLGxNQE6shbwOAzsixirmiUyXBQIDAQAB
AoGAZwCallgGIpBcZn10Q6S2UMQPdi/TYkveyITFfS7Ezsgccd3JV7y9oEvSYi1v
JxW9Jmd5WTITPkE3f7ATlF07cT5EZaHPMHm02GJegopN1AW2caoN2N+FHpe2cnOW
0vLtV+dQ0j5QnCWOfPpM70wYqEwvO+tC9uIaIOCBVTdyF20CQQD7IxTeZjiirZ0M
SlSPZmNRlFBRUkHjc4I7A5weV5L5YR/LWN2W/RL0j+v60L18Uld0pGcDuYX1Fg42
oUYEazaLAkEA+PLEMtU7vh3d9PtyDyIG7prcAJnUljwybRgZoVQNMsMxxONbSoAb
B9tw8irock7zjkPYsqvjSAxcfV1I+J6qrwJBAJaFQEzMF8XpKOfk5SnNxFlw+3LC
Spt47+VPFJNbCcxOWjAW4zlMFcBfQqDh27BX6fMPVm71E0UCIyK7JqwfVmECQAJ8
8qcLaIhy5ff/11j9XxJda9t5rh0+Rsa+Wes52tPqDYJJP21UMHD4qX1SHnaeAWMn
nG/UtfXPYdFC8GrDszMCQHNHjkRPhgnFKZBIqg6CjWE0wVWdZRWwLrP7a2YQsX4A
aZkvLueqxAr5SzU9sTiL6tBQAEaESEHOTm11g+IRmFA=
-----END RSA PRIVATE KEY-----
"""

    def __init__(self):
        self.start_agent()
        self.load_keys()

    def start_agent(self):
        output = subprocess.check_output('ssh-agent')
        self.socket_path = re.search('SSH_AUTH_SOCK=(.+?);', output).group(1)
        pid_str = re.search(r'SSH_AGENT_PID=(\d+)', output).group(1)
        self.agent_pid = int(pid_str)

    def load_keys(self):
        key_name = 'a_test_ssh_key'
        key_file = tempfile.NamedTemporaryFile(
            dir='/tmp',
            prefix=key_name + '.')
        key_file.write(self.TEST_KEY)
        key_file.flush()
        self._ssh_add(key_file.name)

    def delete_keys(self):
        self._ssh_add('-D')

    def _ssh_add(self, *args):
        command = ['ssh-add']
        command.extend(args)
        env = dict(os.environ)
        env['SSH_AUTH_SOCK'] = self.socket_path
        subprocess.check_call(command, env=env, stderr=subprocess.PIPE)

    def stop(self):
        os.kill(self.agent_pid, signal.SIGKILL)


class SSHAgentTest(unittest.TestCase):
    def setUp(self):
        self.ssh_fixture = SSHTestFixture()

    def test_identities(self):
        ssh = SSHAgent(self.ssh_fixture.socket_path)
        keys = ssh.identities()
        self.assertEqual(len(keys), 1, "number of keys loaded in agent")

    def test_sign(self):
        ssh = SSHAgent(self.ssh_fixture.socket_path)
        key = ssh.identities()[0]
        message = "Hello, world!"
        expected_digest = "791c659db0f314126ff0226beaa25aa6b8c4f00e"
        flags = SSHAgent.SIGN_FLAG_NONE
        for _ in range(0, 3):
            signature = ssh.sign(key.blob, message, flags)
            actual_digest = hashlib.sha1(signature).hexdigest()
            self.assertEqual(expected_digest, actual_digest)

    def tearDown(self):
        self.ssh_fixture.stop()


class CipherTest(unittest.TestCase):
    message = 'Hello, world!'

    def assert_encrypt(self, cipher, passphrase):
        reader = io.BytesIO(self.message)
        writer = io.BytesIO()
        cipher.encrypt(reader, writer, passphrase)
        writer.seek(0)
        ciphertext = writer.read()
        return ciphertext

    def assert_decrypt(self, cipher, ciphertext, passphrase):
        reader = io.BytesIO(ciphertext)
        writer = io.BytesIO()
        cipher.decrypt(reader, writer, passphrase)
        writer.seek(0)
        plaintext = writer.read()
        self.assertEqual(self.message, plaintext, cipher.__class__.__name__)


class OpenSSLCipherTest(CipherTest):
    def test_cipher(self):
        cipher = OpenSSLCipher()
        passphrase = 'PASSPHRASE'
        ciphertext = self.assert_encrypt(cipher, passphrase)
        self.assert_decrypt(cipher, ciphertext, passphrase)


class ScryptCipherTest(CipherTest):
    def test_cipher(self):
        cipher = ScryptCipher(encrypt_options=['-t', '0.1'])
        passphrase = 'PASSPHRASE'
        ciphertext = self.assert_encrypt(cipher, passphrase)
        self.assert_decrypt(cipher, ciphertext, passphrase)


class ShovelFileTest(CipherTest):
    def setUp(self):
        self.fixture = SSHTestFixture()

    def tearDown(self):
        self.fixture.stop()

    def test_cipher(self):
        ssh = SSHAgent(self.fixture.socket_path)
        key = ssh.identities()[0]
        message = "Hello, world!!!!1"
        cipher = OpenSSLCipher()
        src = io.BytesIO(message)
        dst = io.BytesIO()
        ShovelFile.encrypt(src, ssh, key, cipher).decrypt(dst, ssh)
        dst.seek(0)
        self.assertEqual(message, dst.read())

    def test_missing_keys(self):
        ssh = SSHAgent(self.fixture.socket_path)
        key = ssh.identities()[0]
        message = "Hello, world!!!!1"
        cipher = OpenSSLCipher()
        src = io.BytesIO(message)
        dst = io.BytesIO()
        shovel_file = ShovelFile.encrypt(src, ssh, key, cipher)
        self.fixture.delete_keys()
        ex = None
        try:
            shovel_file.decrypt(dst, ssh)
        except UserException as ex:
            pass
        self.assertIsNotNone(ex)
        self.assertTrue("key we don't have" in str(ex))


Main(sys.argv[1:])
